#!/usr/bin/env python3
"""
Diagnose and fix alignment between ferry route endpoints and port coordinates.
Routes generated by searoute may start/end at slightly different coordinates
than the actual port locations in ferry_ports.json.
"""
import json
import sys
import os

def load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def save_json(path, data):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

def haversine_km(lat1, lon1, lat2, lon2):
    from math import radians, sin, cos, sqrt, atan2
    R = 6371
    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)
    a = sin(dlat/2)**2 + cos(radians(lat1))*cos(radians(lat2))*sin(dlon/2)**2
    return R * 2 * atan2(sqrt(a), sqrt(1-a))

def normalize(s):
    return s.lower().strip()

def split_route_name(name):
    """Split 'Barcelona - Palma' or 'Stockholm - Mariehamn - Helsinki' into parts."""
    # Handle various dash types
    name = name.replace('\u2013', '-').replace('\u2014', '-').replace('\u2012', '-')
    return [p.strip() for p in name.split(' - ')]

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)
    
    ports_path = os.path.join(project_dir, 'ferry_ports.json')
    ferries_path = os.path.join(project_dir, 'ferries.json')
    
    print("Loading data...")
    ports_data = load_json(ports_path)
    ferries_data = load_json(ferries_path)
    
    # Build port lookup by normalized name
    ports_by_name = {}
    for p in ports_data['ports']:
        name = normalize(p['name'])
        ports_by_name[name] = p
    
    print(f"Ports: {len(ports_by_name)}")
    print(f"Routes: {len(ferries_data['routes'])}")
    
    # First pass: diagnose mismatches
    print("\n=== Diagnosing alignment issues (>1km gap) ===\n")
    mismatches = []
    
    for r in ferries_data['routes']:
        rid = r['id']
        rname = r['name']
        coords = r.get('coords', [])
        if len(coords) < 2:
            continue
        
        parts = split_route_name(rname)
        start_coord = coords[0]
        end_coord = coords[-1]
        
        # Check start port
        if parts:
            start_name = normalize(parts[0])
            if start_name in ports_by_name:
                port = ports_by_name[start_name]
                dist = haversine_km(start_coord[0], start_coord[1], port['lat'], port['lng'])
                if dist > 1.0:
                    mismatches.append({
                        'route_id': rid, 'route_name': rname,
                        'endpoint': 'START', 'port_name': parts[0],
                        'route_coord': start_coord,
                        'port_coord': [port['lat'], port['lng']],
                        'gap_km': dist
                    })
            else:
                # Try fuzzy match
                pass
        
        # Check end port
        if len(parts) >= 2:
            end_name = normalize(parts[-1])
            if end_name in ports_by_name:
                port = ports_by_name[end_name]
                dist = haversine_km(end_coord[0], end_coord[1], port['lat'], port['lng'])
                if dist > 1.0:
                    mismatches.append({
                        'route_id': rid, 'route_name': rname,
                        'endpoint': 'END', 'port_name': parts[-1],
                        'route_coord': end_coord,
                        'port_coord': [port['lat'], port['lng']],
                        'gap_km': dist
                    })
        
        # Check intermediate ports for multi-stop routes
        if len(parts) >= 3:
            for i, port_name in enumerate(parts[1:-1], 1):
                port_name_norm = normalize(port_name)
                if port_name_norm in ports_by_name:
                    port = ports_by_name[port_name_norm]
                    # Find closest coordinate in the route
                    best_dist = float('inf')
                    best_idx = -1
                    for j, c in enumerate(coords):
                        dist = haversine_km(c[0], c[1], port['lat'], port['lng'])
                        if dist < best_dist:
                            best_dist = dist
                            best_idx = j
                    if best_dist > 3.0:
                        mismatches.append({
                            'route_id': rid, 'route_name': rname,
                            'endpoint': f'MID:{port_name}', 'port_name': port_name,
                            'route_coord': coords[best_idx] if best_idx >= 0 else None,
                            'port_coord': [port['lat'], port['lng']],
                            'gap_km': best_dist,
                            'closest_idx': best_idx
                        })
    
    # Print mismatches
    for m in mismatches:
        ep = m['endpoint']
        print(f"  {m['route_id']}: {m['route_name']} [{ep}]")
        print(f"    Route: {m['route_coord']}, Port: {m['port_coord']}, Gap: {m['gap_km']:.1f}km")
    
    print(f"\nTotal mismatches: {len(mismatches)}")
    
    # Second pass: fix mismatches
    if mismatches:
        print("\n=== Fixing alignment ===")
        fixed = 0
        midpoint_fixes = 0
        
        for m in mismatches:
            rid = m['route_id']
            ep = m['endpoint']
            port_coord = m['port_coord']
            
            # Find the route
            route = next((r for r in ferries_data['routes'] if r['id'] == rid), None)
            if not route:
                continue
            
            coords = route.get('coords', [])
            
            if ep == 'START':
                coords[0] = port_coord
                fixed += 1
                print(f"  {rid} START -> {port_coord}")
            elif ep == 'END':
                coords[-1] = port_coord
                fixed += 1
                print(f"  {rid} END -> {port_coord}")
            elif ep.startswith('MID:'):
                # Snap the closest point to the intermediate port
                idx = m.get('closest_idx', -1)
                if idx >= 0 and idx < len(coords):
                    coords[idx] = port_coord
                    midpoint_fixes += 1
                    print(f"  {rid} {ep} (idx {idx}) -> {port_coord}")
        
        print(f"\nFixed {fixed} endpoints + {midpoint_fixes} midpoints")
    
    # Write updated file
    save_json(ferries_path, ferries_data)
    print(f"\nOutput written to: {ferries_path}")


if __name__ == '__main__':
    main()
